### PR TITLE
Fix for sim_build given as absolute path

### PR DESCRIPTION
**Pull request by themperek**
Related to #114

### CODE REVIEW

**Comment by alexforencich** [comment]
This change seems like it assumes that if there is a value passed to `sim_build`, it's an absolute path.  But all of my current scripts pass just a directory name, and that's probably the case for a lot of other folks.  I think we'll need to try to figure out if the specified path is absolute or not and act accordingly.  Alternatively, maybe a couple of different arguments could be used, such as `sim_build_abs` or `sim_build_rel` and then the user can set the correct one depending on if the path is relative or absolute.

**Comment by themperek** [comment]
As far as I know, it will convert `sim_build` to absolute if relative and will be absolute if not? This is how it works for me.

**Comment by alexforencich** [comment]
If nothing is specified, then the var is set to cwd + "sim_build", otherwise it gets set to abspath of whatever was specified. Why are you still doing anything with cwd instead of also using abspath?

**Comment by alexforencich** [comment]
Also, I don't think you can pass an absolute path to abspath. You probably want to do something more along the lines of 

    if not os.path.isabs(sim_build):
        sim_build = os.path.abspath(sim_build)

**Comment by themperek** [comment]
Sorry, I may not understand something:

in `/home`
```
In [1]: os.path.abspath("/tmp/sim")                                                                                                                                                                                                                    
Out[1]: '/tmp/sim'

In [2]: os.path.abspath("sim")                                                                                                                                                                                                                         
Out[2]: '/home/sim'
```

Can you give me an example?

**Comment by alexforencich** [comment]
Never mind then, apparently the python documentation for abspath is crap. Ah any rate, why the if statement? Why not just shove the value through abspath unconditionally?

**Comment by themperek** [comment]
> Why not just shove the value through abspath unconditionally?

You are right. Like now?

**Comment by alexforencich** [comment]
Yes, that looks good.  Sometimes the simplest solution is the best solution.  I just wish the python documentation for abspath was better - it seems to imply that you can only provide a relative path as it will attach it to the cwd and then normalize it, but apparently it only does this to relative paths.  Figures.

**Pull request merged**
